# Mastering NumPy (Part-2)

In [1]:
import numpy as np

In [2]:
empty = np.empty((2,3))
print(empty)
print("--------------")
print(empty[1])

[[3.47739925e-081 2.12856511e+160 1.73296503e+185]
 [7.67662611e-042 1.79177951e+160 1.29441776e-312]]
--------------
[7.67662611e-042 1.79177951e+160 1.29441776e-312]


In [3]:
empty = np.empty((2,4))
print(empty)
print("--------------")
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------
[0. 0. 0. 0.]


In [5]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [8]:
# array of even numbers from 0 to 30
even = np.arange(2, 30, 2)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
# array of odd numbers from  1 to 31
odd_numbers = np.arange(1, 31, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [12]:
# specific differnce between numbers
diff = np.arange(0, 23, 0.15) # o.15 is the difference between numbers
diff

array([ 0.  ,  0.15,  0.3 ,  0.45,  0.6 ,  0.75,  0.9 ,  1.05,  1.2 ,
        1.35,  1.5 ,  1.65,  1.8 ,  1.95,  2.1 ,  2.25,  2.4 ,  2.55,
        2.7 ,  2.85,  3.  ,  3.15,  3.3 ,  3.45,  3.6 ,  3.75,  3.9 ,
        4.05,  4.2 ,  4.35,  4.5 ,  4.65,  4.8 ,  4.95,  5.1 ,  5.25,
        5.4 ,  5.55,  5.7 ,  5.85,  6.  ,  6.15,  6.3 ,  6.45,  6.6 ,
        6.75,  6.9 ,  7.05,  7.2 ,  7.35,  7.5 ,  7.65,  7.8 ,  7.95,
        8.1 ,  8.25,  8.4 ,  8.55,  8.7 ,  8.85,  9.  ,  9.15,  9.3 ,
        9.45,  9.6 ,  9.75,  9.9 , 10.05, 10.2 , 10.35, 10.5 , 10.65,
       10.8 , 10.95, 11.1 , 11.25, 11.4 , 11.55, 11.7 , 11.85, 12.  ,
       12.15, 12.3 , 12.45, 12.6 , 12.75, 12.9 , 13.05, 13.2 , 13.35,
       13.5 , 13.65, 13.8 , 13.95, 14.1 , 14.25, 14.4 , 14.55, 14.7 ,
       14.85, 15.  , 15.15, 15.3 , 15.45, 15.6 , 15.75, 15.9 , 16.05,
       16.2 , 16.35, 16.5 , 16.65, 16.8 , 16.95, 17.1 , 17.25, 17.4 ,
       17.55, 17.7 , 17.85, 18.  , 18.15, 18.3 , 18.45, 18.6 , 18.75,
       18.9 , 19.05,

In [13]:
linear = np.linspace(0, 10, num=5) # it make the line in a specified interval
linear

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# Assighnment: What is the difference between int32,64 and float 32,64,  16.....and meaning?why do we use one and not  the other?

The differences between `int32`, `int64`, `float16`, `float32`, and `float64` lie in their size, range, precision, and typical usage scenarios. Here’s a detailed breakdown:

### Integer Types

1. **`int32`**:
   - **Size**: 32 bits (4 bytes)
   - **Range**: \(-2^{31}\) to \(2^{31}-1\) (approximately -2.1 billion to 2.1 billion)
   - **Usage**: Suitable for most applications requiring whole numbers within this range. Commonly used when memory efficiency is important, and the range is adequate.

2. **`int64`**:
   - **Size**: 64 bits (8 bytes)
   - **Range**: \(-2^{63}\) to \(2^{63}-1\) (approximately -9.2 quintillion to 9.2 quintillion)
   - **Usage**: Used when dealing with very large numbers that exceed the range of `int32`. Necessary for applications like large-scale data processing, high-precision timing, and large financial calculations.

### Floating-Point Types

1. **`float16`** (Half Precision):
   - **Size**: 16 bits (2 bytes)
   - **Range**: Approximately \(6.10 \times 10^{-5}\) to \(6.55 \times 10^4\)
   - **Precision**: About 3-4 decimal digits
   - **Usage**: Used in machine learning models and GPUs where memory efficiency is crucial, and the precision requirement is lower. It allows for faster computations due to smaller size.

2. **`float32`** (Single Precision):
   - **Size**: 32 bits (4 bytes)
   - **Range**: Approximately \(1.18 \times 10^{-38}\) to \(3.4 \times 10^{38}\)
   - **Precision**: About 7-8 decimal digits
   - **Usage**: Commonly used in scientific computations, graphics, and machine learning. Provides a balance between range, precision, and memory usage. Preferred in many applications due to its efficiency and adequate precision.

3. **`float64`** (Double Precision):
   - **Size**: 64 bits (8 bytes)
   - **Range**: Approximately \(2.23 \times 10^{-308}\) to \(1.8 \times 10^{308}\)
   - **Precision**: About 15-16 decimal digits
   - **Usage**: Used in applications requiring high precision and a wide range of values, such as scientific simulations, financial calculations, and certain data analysis tasks. Necessary when precision is critical.

### Why Use One and Not the Other?

#### Memory Usage
- **Smaller Types (`int32`, `float16`, `float32`)**:
  - Consume less memory, which is beneficial when dealing with large datasets or when memory resources are limited.
  - Can lead to faster data processing and computation, especially on GPUs and in parallel processing environments.

- **Larger Types (`int64`, `float64`)**:
  - Consume more memory but provide a larger range and higher precision.
  - Essential when the data values exceed the range of smaller types or when higher precision is required to avoid significant numerical errors.

#### Performance
- **Smaller Types**: Often result in faster computations and reduced memory bandwidth, which is crucial in high-performance computing scenarios like deep learning and real-time processing.
- **Larger Types**: May lead to slower computations due to increased memory usage and more complex arithmetic operations but are necessary for accurate results in certain applications.

#### Precision and Range
- **Integers (`int32`, `int64`)**: Used based on the range of values. For example, `int32` is sufficient for indexing arrays, while `int64` might be needed for counting large items.
- **Floating-Point (`float16`, `float32`, `float64`)**: Chosen based on the required precision and range. `float32` is generally adequate for many applications, but `float64` is used when higher precision is necessary.

### Practical Considerations in Data Science

- **Memory and Performance**: When working with large datasets, using smaller data types can significantly reduce memory usage and increase computational speed. This is particularly important in machine learning and data analytics.
- **Precision**: In applications where numerical precision is crucial, such as financial modeling or scientific simulations, using `float64` can prevent rounding errors and ensure accuracy.
- **Compatibility**: Sometimes the choice of data type is influenced by the requirements of the tools and libraries being used, which might support or optimize for certain data types.

By carefully selecting the appropriate data type, you can optimize both the performance and accuracy of your programs.

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [16]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [18]:
#  concatenate them with np.concatenate().
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

# Concatenate 2D Arrays

In [19]:
x = np.array([[1, 2], [3, 4]])  # 2*2 array
y = np.array([[5, 6]])         # 1*2 array

In [20]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
w = np.array([[5,1], [7,1]])
x = np.array([[1, 2], [3, 4]])  # 2*2 array

In [22]:
z1 = np.concatenate((w,x),axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])