# Numpy Introduction

In [2]:
# pip install  numpy
import numpy as np

# What is an array?

An array is a data structure that stores a collection of items of the same type in contiguous memory locations. It allows you to store multiple elements of the same data type under a single variable name. Each element in an array is accessed by its index, which represents its position in the array. Arrays are widely used in programming because they provide efficient access to elements and facilitate operations such as traversal, searching, and sorting.

In [8]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [19]:
a2 = a[:, np.newaxis]
print(a2.shape)
# Transpose the array
arr_transpose =a2.reshape(1, -1)
print(arr_transpose)

(6, 1)
[[0 1 2 3 4 5]]


In [ ]:
a2 = a[np.newaxis]
print(a2)
a2.shape

In [17]:
a3 = a2[np.newaxis]
print(a3.shape)
# Transpose the array
arr_transpose2 =a3.reshape(1, -1)
print(arr_transpose2)

(1, 6, 1)
[[0 1 2 3 4 5]]


# Assighnment: why do we have 1D, 2D or 3D arrays and where we need them in data science?

The distinctions between 1D, 2D, and 3D arrays relate to the number of dimensions or axes they have. Each dimension represents a different aspect of the data. Here's a brief overview:

1. **1D Array (One-dimensional array)**:
   - Also known as a vector.
   - It has a single dimension, like a list.
   - Example: `[1, 2, 3, 4, 5]`.
   - Used for representing sequences of data or a single feature in machine learning models.

2. **2D Array (Two-dimensional array)**:
   - Also known as a matrix.
   - It has two dimensions, represented as rows and columns.
   - Example: 
     ```
     [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
     ```
   - Used for representing datasets, tables, images, and matrices in linear algebra. Commonly used in data manipulation, data analysis, and machine learning.

3. **3D Array (Three-dimensional array)**:
   - It has three dimensions, represented as depth, rows, and columns.
   - Example:
     ```
     [[[1, 2],
       [3, 4]],
     
      [[5, 6],
       [7, 8]],
     
      [[9, 10],
       [11, 12]]]
     ```
   - Used for representing volumes, time series data, video data, and sometimes as higher-dimensional matrices in certain mathematical operations.

In data science, these different types of arrays are crucial because they allow us to represent and manipulate various types of data efficiently. For instance:

- **1D arrays** are often used to represent individual data points, such as features or labels in machine learning algorithms.

- **2D arrays** are fundamental for tabular data, such as datasets stored in spreadsheets or databases. They are extensively used in data preprocessing, exploratory data analysis, and as input or output data for machine learning models.

- **3D arrays** are employed for more complex data structures like sequences of images, volumes of medical imaging data, or time series data. They are common in deep learning applications, where neural networks process sequences of data points, such as frames in a video or slices in a 3D image.


# Creating Arrays with Numpy

In [3]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7), (4,5,6,7,8,9,10)])

In [17]:
type(a) # type of array

numpy.ndarray

In [11]:
a.dtype  # data type of array elements

dtype('int32')

In [12]:
b.dtype

dtype('int32')

In [6]:
print(a )
a.shape

[1 2 3 4 5 6 7]


(7,)

In [5]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# Initialize arrays

In [7]:
zeros = np.zeros((3,4)) # (rows, columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
zeros.dtype

dtype('float64')

In [8]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [9]:
full = np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
full.dtype

dtype('int32')

In [10]:
identity = np.eye(5) # creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
identity.dtype

dtype('float64')

# array attributes

In [18]:
a.shape # shape of array

(7,)

In [19]:
len(a) # give us the length elements in array

7

In [21]:
a.size # gives us the numbers of elements in array

7

In [20]:
b.ndim # give us the dimension of array

2

# basic opperations

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [25]:
g = a-b
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [26]:
h = a + b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [28]:
# we can also add inthis way
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [29]:
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [30]:
y = a / b
y

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
r = a ** 2
r

array([ 1,  4,  9, 16, 25, 36, 49])