# Numpy_Indexing and slicing

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
a[0]

1

In [12]:
a[1:5]

array([2, 3, 4, 5])

In [8]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# np.arange(0, 12, 2)
# Start: 0
# Stop: 12 (exclusive)
# Step: 2
# The sequence will be generated as follows:

# Start at 0
# Add the step value (2): 0 + 2 = 2
# Add the step value again: 2 + 2 = 4
# Continue adding the step value: 4 + 2 = 6
# Continue adding the step value: 6 + 2 = 8
# Continue adding the step value: 8 + 2 = 10
# The next value would be 10 + 2 = 12, but since 12 is the stop value and the stop value is exclusive, the sequence ends before including 12.

In [10]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [11]:
c[0]

array([0, 2, 4])

In [13]:
c1 = b.reshape(3,2)
c1

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
c1[1]

array([4, 6])