# How to create an array from existing data

In [1]:
import numpy as np

In [3]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [6]:
len(a)

45

In [8]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [9]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [10]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
d2 = d.reshape(2,7)
d2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])