# Linear algebra in Python for Data Science| Zero-to-Math series 

In [1]:
import numpy as np
import pandas as pd

2x+3y=8

5x+4y=20

In [4]:
# coficient maticx A
A = np.array([[2,3],[5,4]])  # 2*2 matrix
A

array([[2, 3],
       [5, 4]])

In [3]:
# constant matrix B
B = np.array([8,20])
B

array([ 8, 20])

In [5]:
# solve for x 
x = np.linalg.solve(A,B)  # Solve for x
x

array([4., 0.])

----
# solving complex equations