# NumPy: the absolute basics for beginners

In [1]:
import numpy as np

# How to create a basic array

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(2)


array([1., 1.])

In [5]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [6]:
# we can create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [7]:
# 
np.arange(2,9,2)

array([2, 4, 6, 8])

In [9]:
np.linspace(0, 10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# Adding, removing, and sorting elements

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.argsort(a, axis=-1, kind=None, order=None)

# Numpy quick start

In [11]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
a.shape

(3, 5)

In [13]:
a.ndim

2

In [16]:
a.dtype.name

'int32'

In [19]:
a.itemsize

4

In [20]:
a.size

15

In [21]:
type(a)

numpy.ndarray

In [22]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2, 3, 4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.empty((2, 3)) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [27]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [28]:
np.arange(0, 2, 0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [29]:
np.linspace(0, 2, 9)  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

NameError: name 'pi' is not defined