# NumPy: the absolute basics for beginners

In [1]:
import numpy as np

# How to create a basic array

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(2)


array([1., 1.])

In [5]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [6]:
# we can create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [7]:
# 
np.arange(2,9,2)

array([2, 4, 6, 8])

In [9]:
np.linspace(0, 10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# Adding, removing, and sorting elements

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.argsort(arr, axis=-1, kind=None, order=None)

array([1, 0, 3, 5, 2, 6, 4, 7], dtype=int64)

In [8]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5])
sorted_indices = arr.argsort()  # sorted_indices = [1, 0, 2, 0, 3]

print(arr[sorted_indices])  # Output: [1 1 3 4 5] (sorted version)


[1 1 3 4 5]


In [9]:
arr = np.array([['Alice', 25], ['Bob', 30], ['Charlie', 25]])
names, ages = arr[:, 0], arr[:, 1]  # Separate keys
sorted_indices = np.lexsort([ages, names])

print(arr[sorted_indices])  # Output: [['Alice', 25], ['Charlie', 25], ['Bob', 30]] (sorted by age, then name for ties)


[['Alice' '25']
 ['Bob' '30']
 ['Charlie' '25']]


In [10]:
sorted_arr = np.array([1, 3, 5, 7])
search_values = [2, 4, 8]

left_indices = sorted_arr.searchsorted(search_values, side='left')  # [1, 3, 4]
right_indices = sorted_arr.searchsorted(search_values, side='right')  # [1, 3, 4]

print(left_indices)  # Where to insert to maintain order from the left
print(right_indices)  # Where to insert to maintain order from the right


[1 2 4]
[1 2 4]


In [ ]:
arr = np.array([4, 2, 8, 1, 5])
pivot_index = arr.partition(arr[2])  # Partition around the element at index 2

print(arr)  # Possibly rearranged array, pivot at pivot_index (may vary)


# concatenate them with np.concatenate().

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

### axis=0: Stacks arrays vertically (increasing rows).
### axis=1: Stacks arrays horizontally (increasing columns).
### axis=None: Flattens arrays into 1D and concatenates them

In [23]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)



array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:

np.concatenate((a, b.T), axis=1)



array([[1, 2, 5],
       [3, 4, 6]])

In [25]:

np.concatenate((a, b), axis=None)


array([1, 2, 3, 4, 5, 6])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

# np.newaxis

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

### np.newaxis creates a new axis in the array.
### np.newaxis adds a new axis.
### : selects all elements along that axis.

In [4]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a2 = a[np.newaxis, :]

In [6]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [9]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [7]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [8]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# np.expand_dims

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [12]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [13]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [15]:
c

array([[1, 2, 3, 4, 5, 6]])

# How do you know the shape and size of an array?

In [26]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [27]:
a.ndim

3

In [28]:
a.dtype

dtype('int32')

In [29]:
a.size

24

In [30]:
a.shape

(3, 2, 4)

# reshape an array

In [32]:
a = np.arange(6)
a


array([0, 1, 2, 3, 4, 5])

In [34]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
np.reshape(a, newshape=(1, 6), order='C')  # This is an optional parameter and doesn’t need to be specified.

array([[0, 1, 2, 3, 4, 5]])

# Indexing and slicing

In [21]:
a = np.array([1, 2, 3])
a


array([1, 2, 3])

In [19]:
a[2]

3

In [23]:
a[0:2]

array([1, 2])

In [24]:
a[1:]

array([2, 3])

In [25]:
a[-2:]

array([2, 3])

In [27]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
a[a<5]

array([1, 2, 3, 4])

In [30]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

# Numpy quick start

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
a.shape

(3, 5)

In [13]:
a.ndim

2

In [16]:
a.dtype.name

'int32'

In [19]:
a.itemsize

4

In [20]:
a.size

15

In [21]:
type(a)

numpy.ndarray

In [22]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2, 3, 4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.empty((2, 3)) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [27]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [28]:
np.arange(0, 2, 0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [29]:
np.linspace(0, 2, 9)  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

NameError: name 'pi' is not defined