# Matrices in python in numpy library

In [1]:
import numpy as np

In [2]:
# creating 2*3 matrices
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a1


array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# creating 3*2 matrices
a = np.array([[1, 2], [3, 4], [5, 6]])
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a[1]

array([3, 4])

In [5]:
# creating a matrix of big dimension
b = np.arange(0, 100, 2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [6]:
b1 = np.arange(0, 100, 2).reshape(5,10)
b1

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])


### General Slicing Syntax

In NumPy, the general slicing syntax for a 2D array `array` is:

```python
array[start_row:end_row, start_col:end_col]
```

- `start_row:end_row`: Selects rows from `start_row` to `end_row - 1`.
- `start_col:end_col`: Selects columns from `start_col` to `end_col - 1`.

This powerful slicing syntax allows you to easily extract subarrays and work with specific parts of your data efficiently.

In [7]:
c = b1[2:3, 4:5]
c


array([[48]])

In [8]:
# slicing a matrices
c1 = b1[1:3, 3:5]
c1


array([[26, 28],
       [46, 48]])

In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
arr[0:2, 2]

array([3, 8])

In [32]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# aggregate matrices the same way you aggregated vectors:

In [9]:
b1.max()

98

In [10]:
b1.min()

0

In [11]:
b1.sum()

2450

In [12]:
b1

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [13]:
b1.max(axis=0) # only for column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
b1.max(axis=1) # only for rows

array([18, 38, 58, 78, 98])

In [15]:
b1.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
b1.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [17]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [18]:
m + np.array([20,22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [19]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

# How to reverse an array

In [20]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [21]:
np.flip(b)

array([98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66,
       64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32,
       30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

# Assighnment: Do basic numpy library

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,])

print(arr[1:5:2])

[2 4]


In [24]:
arr = np.array([5, 6, 7, 8, 9, 10, 11])

arr[1:5:2]

array([6, 8])

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]
