# NAIVE Bayes algorithm

Naive Bayes Algorithm is a classification algorithm based on Bayes Theorem. It is called naive because it assumes that the features in a dataset are independent of each other. This assumption is not true in real life but it simplifies the computation and gives good results in most of the cases.

## Bayes Theorem

Bayes Theorem is a mathematical formula used for calculating conditional probability. It is defined as:

$$P(A|B) = \frac{P(B|A)P(A)}{P(B)}$$

where A and B are events and P(B) != 0

## Naive Bayes Algorithm

Naive Bayes Algorithm is based on Bayes Theorem. It is defined as:

$$P(y|x_1,x_2,...,x_n) = \frac{P(x_1,x_2,...,x_n|y)P(y)}{P(x_1,x_2,...,x_n)}$$

where y is the class variable and x1, x2, ..., xn are the features.

The algorithm assumes that the features are independent of each other. So, the above equation can be written as:

$$P(y|x_1,x_2,...,x_n) = \frac{P(x_1|y)P(x_2|y)...P(x_n|y)P(y)}{P(x_1,x_2,...,x_n)}$$

The denominator is constant for a given input. So, the equation can be written as:

$$P(y|x_1,x_2,...,x_n) \propto P(x_1|y)P(x_2|y)...P(x_n|y)P(y)$$

The class with the highest probability is the output of the algorithm.

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [ ]:
# load the dataset

iris = load_iris()
X = iris.data
y = iris.target

# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
# model initialize
gnb = GaussianNB()

# train the model
gnb.fit(X_train, y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  0.9777777777777777
Confusion Matrix: 
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [6]:
# model initialize
mnb = MultinomialNB()

# train the model
mnb.fit(X_train, y_train)

# predict the test data
y_pred = mnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  0.9555555555555556
Confusion Matrix: 
 [[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [7]:
# model initialize
bnb = BernoulliNB()

# train the model
bnb.fit(X_train, y_train)

# predict the test data
y_pred = bnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  0.28888888888888886
Confusion Matrix: 
 [[ 0 19  0]
 [ 0 13  0]
 [ 0 13  0]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.29      1.00      0.45        13
           2       0.00      0.00      0.00        13

    accuracy                           0.29        45
   macro avg       0.10      0.33      0.15        45
weighted avg       0.08      0.29      0.13        45



/Users/babaaammar/mambaforge/envs/python_ml/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/babaaammar/mambaforge/envs/python_ml/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/babaaammar/mambaforge/envs/python_ml/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

The **Naive Bayes** algorithm is a family of probabilistic classifiers based on **Bayes' Theorem**. It is famous for being incredibly fast, simple to implement, and surprisingly effective for high-dimensional data like text.

The "Naive" part of the name comes from a bold assumption: it assumes that every feature in your dataset is **completely independent** of every other feature.

---

## 1. The Mathematical Foundation: Bayes' Theorem

At its core, Naive Bayes calculates the probability that an event will occur, given that another event has already occurred.

$$P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}$$

In machine learning terms, we use it like this:

* **$P(Class|Features)$:** The probability that a row belongs to a certain class (e.g., "Spam") given its features (the words in the email).
* **$P(Features|Class)$:** The likelihood—how often these features appear in that class.
* **$P(Class)$:** The "Prior" probability—how common the class is in general.
* **$P(Features)$:** The "Evidence"—how common the features are across all data.

---

## 2. Why is it called "Naive"?

Imagine you are identifying a fruit. It is **red**, **round**, and **about 3 inches in diameter**.

* A "Smart" model knows that if a fruit is red and round, it’s more likely to be an apple.
* **Naive Bayes** treats these features as if they have nothing to do with each other. It calculates the probability of "Red," the probability of "Round," and the probability of "3 inches" separately and multiplies them together.

Even though this assumption is almost always false in the real world (features are usually correlated), Naive Bayes still performs remarkably well, especially for **Sentiment Analysis** and **Spam Filtering**.

---

## 3. The Different "Flavors" of Naive Bayes

Depending on the nature of your features, you must choose the right version:

| Version | Best For... | Example |
| --- | --- | --- |
| **Gaussian Naive Bayes** | Continuous/Numerical data that follows a Normal Distribution. | Predicting Iris flower species based on petal length/width. |
| **Multinomial Naive Bayes** | Discrete data, specifically **word counts**. | Spam detection or classifying news articles into categories. |
| **Bernoulli Naive Bayes** | Binary/Boolean features (Yes/No). | Identifying if a specific word is *present* or *absent* in a document. |

---

## 4. Pros and Cons

**Pros:**

* **Lightning Fast:** It is much faster than Random Forests or SVMs.
* **Scalability:** It can handle millions of features easily (very important for NLP).
* **Small Data:** It works well even if you don't have a massive training set.

**Cons:**

* **Independence Assumption:** If your features are highly correlated (e.g., "Age" and "Years of Experience"), Naive Bayes will struggle.
* **Zero Frequency Problem:** If a category in the test set wasn't in the training set, the probability becomes 0, and the model can't make a prediction. (We fix this with **Laplace Smoothing**).

---

## 5. Python Implementation

Since you are a Data Scientist, you'll likely use `GaussianNB` or `MultinomialNB` from `scikit-learn`.

```python
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# 1. Initialize the model
nb_model = GaussianNB()

# 2. Fit and Predict
nb_model.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)

# 3. Evaluate
print(classification_report(y_test, y_pred))

```

---

### Why this fits your portfolio?

For your **IMDB Global Film Dataset** project, Naive Bayes is a perfect baseline model for **Genre Prediction** based on movie descriptions. Because movie plots involve thousands of unique words, Naive Bayes' speed and ability to handle high-dimensional text data make it a top contender.

**Would you like me to show you how to apply "Laplace Smoothing" to handle those words that appear in the test set but were never seen during training?**

At its most basic level, **Bayes' Theorem** is a mathematical formula used to determine the probability of an event based on prior knowledge of conditions that might be related to that event.

In data science, we use it to update our "beliefs" as we get new evidence.

---

## 1. The Core Concept: "Updating Beliefs"

Imagine you are a doctor. A patient comes in with a cough.

* **Prior Probability:** Before checking anything, you know that 5% of people in the city have the flu.
* **New Evidence:** The patient has a high fever.
* **Posterior Probability:** Now that you have the "evidence" (fever), your "belief" that they have the flu increases from 5% to, say, 60%.

Bayes' Theorem is the math that tells you exactly how much that probability should change.

---

## 2. The Formula

The formula looks like this:

$$P(A|B) = \frac{P(B|A) \times P(A)}{P(B)}$$

### Breaking down the terms:

* **$P(A|B)$ (Posterior):** The probability of event $A$ happening **given** that $B$ has already happened. (e.g., Probability of Flu given a Fever).
* **$P(B|A)$ (Likelihood):** The probability of $B$ happening given that $A$ is true. (e.g., How many people with Flu actually get a Fever?).
* **$P(A)$ (Prior):** The initial probability of $A$ before seeing any evidence. (e.g., General rate of Flu in the population).
* **$P(B)$ (Evidence):** The total probability of $B$ happening under all conditions. (e.g., How many people in total have a fever, for any reason?).

---

## 3. Real-World Example: Medical Testing

This is the classic "False Positive" problem that every Data Scientist must understand.

**The Scenario:**

* **1%** of the population has a rare disease ($P(A) = 0.01$).
* A test is **99%** accurate ($P(B|A) = 0.99$).
* The test has a **5%** false positive rate ($P(B|\text{not } A) = 0.05$).

**The Question:** If you test positive, what is the actual chance you have the disease?
Most people guess 99%. **Bayes' Theorem says it is only about 16%.**

**Why?** Because the disease is so rare ($1\%$) that the $5\%$ of healthy people getting false positives far outnumbers the $1\%$ of sick people getting true positives.

---

## 4. Why is it important for you?

As a **Data Scientist**, Bayes' Theorem is the "engine" behind:

1. **Naive Bayes Classifiers:** Used for your IMDB text analysis and Spam filtering.
2. **A/B Testing:** Deciding if a new website feature is actually better.
3. **Bayesian Optimization:** The logic behind **Optuna** that we discussed for hyperparameter tuning.

---

### Summary Table

| Term | Simple Definition |
| --- | --- |
| **Prior** | What we knew before the new data. |
| **Likelihood** | How well the data fits our theory. |
| **Posterior** | What we believe now, after seeing the data. |

**Would you like me to show you how to solve a simple Bayesian word problem using Python to see the math in action?**