# Pre-algebra for Data Science part 3 | Zero-to-Math series

# Assighnment 1: Metric and Imperial Units

The Metric and Imperial systems are two different measurement systems used around the world. Here’s an overview of both:

### Metric System
The Metric System, also known as the International System of Units (SI), is used by most countries and is based on units of 10. Here are the main units:

1. **Length**:
   - Millimeter (mm)
   - Centimeter (cm)
   - Meter (m)
   - Kilometer (km)

2. **Mass**:
   - Milligram (mg)
   - Gram (g)
   - Kilogram (kg)
   - Metric Ton (t)

3. **Volume**:
   - Milliliter (mL)
   - Liter (L)
   - Cubic meter (m³)

4. **Temperature**:
   - Degrees Celsius (°C)

5. **Area**:
   - Square meter (m²)
   - Hectare (ha)

### Imperial System
The Imperial System is primarily used in the United States and a few other countries. Here are the main units:

1. **Length**:
   - Inch (in)
   - Foot (ft)
   - Yard (yd)
   - Mile (mi)

2. **Mass/Weight**:
   - Ounce (oz)
   - Pound (lb)
   - Ton (short ton, US ton)

3. **Volume**:
   - Teaspoon (tsp)
   - Tablespoon (tbsp)
   - Fluid ounce (fl oz)
   - Cup
   - Pint (pt)
   - Quart (qt)
   - Gallon (gal)
   - Cubic foot (ft³)

4. **Temperature**:
   - Degrees Fahrenheit (°F)

5. **Area**:
   - Square inch (in²)
   - Square foot (ft²)
   - Square yard (yd²)
   - Acre

### Converting Between Metric and Imperial Units
Here are some common conversions between the Metric and Imperial systems:

1. **Length**:
   - 1 inch = 2.54 centimeters
   - 1 foot = 0.3048 meters
   - 1 yard = 0.9144 meters
   - 1 mile = 1.60934 kilometers

2. **Mass/Weight**:
   - 1 ounce = 28.3495 grams
   - 1 pound = 0.453592 kilograms
   - 1 ton (US) = 907.185 kilograms

3. **Volume**:
   - 1 teaspoon = 4.92892 milliliters
   - 1 tablespoon = 14.7868 milliliters
   - 1 fluid ounce = 29.5735 milliliters
   - 1 cup = 236.588 milliliters
   - 1 pint = 473.176 milliliters
   - 1 quart = 0.946353 liters
   - 1 gallon = 3.78541 liters

4. **Temperature**:
   - \( \text{°F} = \text{°C} \times \frac{9}{5} + 32 \)
   - \( \text{°C} = (\text{°F} - 32) \times \frac{5}{9} \)

These conversions help in understanding and converting measurements between the two systems.

# Probability

Probability is a measure of the likelihood that an event will occur. It is quantified as a number between 0 and 1, where 0 indicates that the event will not occur and 1 indicates certainty that the event will occur. Here’s a brief overview of the key concepts in probability:

### Basic Concepts

1. **Experiment**: An action or process that leads to one or several outcomes. For example, rolling a die.

2. **Outcome**: A possible result of an experiment. For example, getting a 4 when rolling a die.

3. **Event**: A set of one or more outcomes. For example, getting an even number when rolling a die (which includes 2, 4, and 6).

4. **Sample Space (\(S\))**: The set of all possible outcomes of an experiment. For a six-sided die, the sample space is \( S = \{1, 2, 3, 4, 5, 6\} \).

5. **Probability of an Event (\(P(E)\))**: The likelihood of the event \( E \) occurring. It is calculated by:
   \[
   P(E) = \frac{\text{Number of favorable outcomes}}{\text{Total number of possible outcomes}}
   \]

### Types of Probability

1. **Theoretical Probability**: Based on reasoning and the nature of the experiment. For example, the probability of rolling a 3 on a fair six-sided die is:
   \[
   P(\text{rolling a 3}) = \frac{1}{6}
   \]

2. **Experimental Probability**: Based on actual experiments and observations. It is calculated by:
   \[
   P(E) = \frac{\text{Number of times event E occurs}}{\text{Total number of trials}}
   \]

3. **Subjective Probability**: Based on intuition, experience, or judgment.

### Important Rules and Formulas

1. **Complement Rule**: The probability of the complement of an event \( E \) (not \( E \)) is:
   \[
   P(\text{not } E) = 1 - P(E)
   \]

2. **Addition Rule**: For any two events \( A \) and \( B \):
   \[
   P(A \text{ or } B) = P(A) + P(B) - P(A \text{ and } B)
   \]

   If \( A \) and \( B \) are mutually exclusive (they cannot happen at the same time):
   \[
   P(A \text{ or } B) = P(A) + P(B)
   \]

3. **Multiplication Rule**: For any two independent events \( A \) and \( B \):
   \[
   P(A \text{ and } B) = P(A) \times P(B)
   \]

### Examples

1. **Single Event**: What is the probability of drawing an ace from a standard deck of 52 cards?
   \[
   P(\text{ace}) = \frac{4}{52} = \frac{1}{13}
   \]

2. **Multiple Events**: What is the probability of rolling a 3 or a 5 on a six-sided die?
   \[
   P(\text{3 or 5}) = P(\text{3}) + P(\text{5}) = \frac{1}{6} + \frac{1}{6} = \frac{2}{6} = \frac{1}{3}
   \]

3. **Complementary Events**: What is the probability of not rolling a 6 on a six-sided die?
   \[
   P(\text{not 6}) = 1 - P(\text{6}) = 1 - \frac{1}{6} = \frac{5}{6}
   \]

Understanding these basic concepts and rules can help you solve a wide range of probability problems.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
print(arr.shape)

(2, 4)


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
